# Generated by Django 5.2.7 on 2025-10-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titolo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('type', models.CharField(choices=[('referendum', 'Referendum'), ('survey', 'Sondaggio'), ('election', 'Elezione'), ('consultation', 'Consultazione')], default='referendum', max_length=50, verbose_name='Tipo')),
                ('start_date', models.DateTimeField(verbose_name='Data Inizio')),
                ('end_date', models.DateTimeField(verbose_name='Data Fine')),
                ('is_active', models.BooleanField(default=True, help_text='Se False, non è possibile votare', verbose_name='Attiva')),
                ('results_public', models.BooleanField(default=False, help_text='Se True, i risultati sono visibili a tutti', verbose_name='Risultati Pubblici')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voting_sessions', to='authentication.municipality', verbose_name='Comune')),
            ],
            options={
                'verbose_name': 'Sessione di Votazione',
                'verbose_name_plural': 'Sessioni di Votazione',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Testo')),
                ('display_order', models.IntegerField(default=0, help_text='Ordine di visualizzazione nella scheda (più basso = prima)', verbose_name='Ordine Visualizzazione')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL Immagine')),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.votingsession', verbose_name='Sessione di Votazione')),
            ],
            options={
                'verbose_name': 'Opzione',
                'verbose_name_plural': 'Opzioni',
                'ordering': ['voting_session', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='CitizenHasVoted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Ora Voto')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voted_sessions', to='authentication.citizen', verbose_name='Cittadino')),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voters', to='voting.votingsession', verbose_name='Sessione di Votazione')),
            ],
            options={
                'verbose_name': 'Cittadino Ha Votato',
                'verbose_name_plural': 'Cittadini Hanno Votato',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Data e Ora')),
                ('session_hash', models.CharField(help_text='Random hash per evitare correlazioni temporali', max_length=64, verbose_name='Hash Sessione')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='voting.option', verbose_name='Opzione Scelta')),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='voting.votingsession', verbose_name='Sessione di Votazione')),
            ],
            options={
                'verbose_name': 'Risultato',
                'verbose_name_plural': 'Risultati',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['voting_session'], name='voting_resu_voting__270c87_idx'), models.Index(fields=['option'], name='voting_resu_option__249800_idx'), models.Index(fields=['timestamp'], name='voting_resu_timesta_2f5fd5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['voting_session', 'display_order'], name='voting_opti_voting__f20173_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenhasvoted',
            index=models.Index(fields=['citizen', 'voting_session'], name='voting_citi_citizen_5f0fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='citizenhasvoted',
            index=models.Index(fields=['voting_session'], name='voting_citi_voting__9e4bc9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='citizenhasvoted',
            unique_together={('citizen', 'voting_session')},
        ),
    ]
