# Generated by Django 5.2.7 on 2025-10-24 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome Comune')),
                ('ipa_code', models.CharField(help_text='Codice IPA del comune (es: c_h501)', max_length=50, unique=True, verbose_name='Codice IPA')),
                ('cap', models.CharField(max_length=255, verbose_name='CAP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
            ],
            options={
                'verbose_name': 'Comune',
                'verbose_name_plural': 'Comuni',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_code_hash', models.CharField(db_index=True, help_text='SHA-256 hash del codice fiscale', max_length=64, unique=True, verbose_name='Hash Codice Fiscale')),
                ('fiscal_code_encrypted', models.TextField(verbose_name='Codice Fiscale Criptato')),
                ('email_encrypted', models.TextField(blank=True, null=True, verbose_name='Email Criptata')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Data Registrazione')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citizens', to='authentication.municipality', verbose_name='Comune')),
            ],
            options={
                'verbose_name': 'Cittadino',
                'verbose_name_plural': 'Cittadini',
                'ordering': ['-registration_date'],
                'indexes': [models.Index(fields=['fiscal_code_hash'], name='authenticat_fiscal__718acf_idx'), models.Index(fields=['municipality'], name='authenticat_municip_85d582_idx')],
            },
        ),
    ]
